version: '3'
services:
  postgres:
    restart: always
    image: postgres:11
    container_name: postgres
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    privileged: true  #解决权限
    environment:
      POSTGRES_PASSWORD: postgres #设置密码
      PGDATA: /var/lib/postgresql/data/pgdata #数据存储文件夹
    ports:
      - 5432:5432
    volumes:
      - /docker-env/postgres/data/db:/var/lib/postgresql/data/pgdata #数据文件挂载
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /docker-env/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /docker-env/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /docker-env/mysql/log:/var/log/mysql #日志文件挂载
#  redis:
#    image: redis:5
#    container_name: redis
#    command: redis-server --appendonly yes
#    volumes:
#      - /docker-env/redis/data:/data #数据文件挂载
#    ports:
#      - 6379:6379
  nginx:
    restart: always
    image: nginx:1.10
    container_name: nginx
    volumes:
      - /docker-env/nginx/conf:/etc/nginx #配置文件挂载
      - /docker-env/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - /docker-env/nginx/log:/var/log/nginx #日志文件挂载
      - /docker-env/nginx/data:/var/nginx/data #项目文件存放路径
    ports:
      - 80:80
      - 443:443
#  rabbitmq:
#    image: rabbitmq:3.7.15-management
#    container_name: rabbitmq
#    volumes:
#      - /docker-env/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
#      - /docker-env/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
#    ports:
#      - 5672:5672
#      - 15672:15672
#  elasticsearch:
#    image: elasticsearch:7.6.2
#    container_name: elasticsearch
#    environment:
#      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
#      - "discovery.type=single-node" #以单一节点模式启动
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
#    volumes:
#      - /docker-env/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - /docker-env/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
#    ports:
#      - 9200:9200
#      - 9300:9300
#  logstash:
#    image: logstash:7.6.2
#    container_name: logstash
#    environment:
#      - TZ=Asia/Shanghai
#    volumes:
#      - /docker-env/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
#    depends_on:
#      - elasticsearch #kibana在elasticsearch启动之后再启动
#    links:
#      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
#    ports:
#      - 4560:4560
#      - 4561:4561
#      - 4562:4562
#      - 4563:4563
#  kibana:
#    image: kibana:7.6.2
#    container_name: kibana
#    links:
#      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
#    depends_on:
#      - elasticsearch #kibana在elasticsearch启动之后再启动
#    environment:
#      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
#    ports:
#      - 5601:5601
#  mongo:
#    image: mongo:4.2.5
#    container_name: mongo
#    volumes:
#      - /docker-env/mongo/db:/data/db #数据文件挂载
#    ports:
#      - 27017:27017