#端口
server:
  port: 7070
spring:
  datasource:
    #1.数据库配置 默认数据连接池是 HikariCP
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源
    url: jdbc:${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:royal_canin}?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #2.连接池配置
    druid:
      initial-size: 10 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 100 #最大连接数
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        enabled: true
        login-username: druid
        login-password: druid
  redis:
    enabled: true #自定义key 是否启用redis
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: admin

  quartz:
    # quartz db schema
    job-store-type: jdbc
    #quartz第一次启动时需要初始化，使用always，之后使用never
    #jdbc.initialize-schema=never
    jdbc.initialize-schema: always

logging:
  level:
    root: info
    com.youjun.api: info

logstash:
  host: logstash