spring:
  datasource:
    url: jdbc:mysql://hzhetundb-dev.mysql.rds.aliyuncs.com:3306/royal_canin?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: hzhetun_dev_team
    password: HT86778673*!*
    druid:
      initial-size: 10 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 100 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  influx:
    url: http://localhost:8086
    database: royal-canin
    user: admin
    password: admin

  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost